version: 2

project_name: nixstasis

git:
  ignore_tags:
    - "caddy/*"
    - "client/*"
    - "frp/*"
    - "server/*"

snapshot:
  version_template: "0.0.0-snapshot-{{ .ShortCommit }}"

builds:
  - id: nixstasis
    binary: usr/bin/nixstasis
    main: ./cmd/nixstasis
    env:
      - CGO_ENABLED=0
      - GOEXPERIMENT=jsonv2
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    hooks:
      post:
        - cmd: bash -x ./build/bin/fetch_frpc.sh {{ .Arch }}

archives:
  - id: nixstasis-archive
    ids:
      - nixstasis
    formats: [tar.gz]
    files:
      - src: build/root-dir/**/*
        dst: .
      - src: dist/frp/frpc_{{ .Arch }}
        dst: usr/libexec/nixstasis/frpc

nfpms:
  - id: nixstasis
    ids:
      - nixstasis
    package_name: nixstasis
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: RobertDeRose
    homepage: https://github.com/RobertDeRose/Nixstasis
    description: Nixstasis client with bundled frpc
    maintainer: Robert DeRose <RobertDeRose@users.noreply.github.com>
    license: Proprietary
    bindir: /
    formats:
      - deb
      - rpm
    scripts:
      postinstall: ./build/debian/postinstall.sh
      preremove: ./build/debian/preremove.sh
    contents:
      - src: build/root-dir/**/*
        dst: .
      - src: dist/frp/frpc_{{ .Arch }}
        dst: usr/libexec/nixstasis/frpc


makeselfs:
  - id: nixstasis-installer
    ids:
      - nixstasis
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    name: nixstasis
    description: Nixstasis client with bundled frpc
    filename: "nixstasis-{{ .Version }}-{{ .Os }}-{{ .Arch }}.run"
    script: build/makeself/entrypoint.sh
    extra_args:
      - "--nox11"
      - "--needroot"
      - "--target"
      - "/"
    files:
      - src: build/root-dir/**/*
        dst: .
      - src: dist/frp/frpc_{{ .Arch }}
        dst: usr/libexec/nixstasis/frpc
      - src: build/debian/postinstall.sh
        dst: usr/libexec/nixstasis/postinstall.sh
      - src: build/makeself/cleanup.sh
        dst: usr/libexec/nixstasis/cleanup.sh
