import Config
config :ash, policies: [show_policy_breakdowns?: true]

bind_all? = String.downcase(System.get_env("NIXSTASIS_DEV_BIND_ALL", "false")) in ["1", "true", "yes"]
endpoint_ip = if bind_all?, do: {0, 0, 0, 0}, else: {127, 0, 0, 1}

# Configure your database
config :nixstasis, Nixstasis.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "nixstasis_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :nixstasis, NixstasisWeb.Endpoint,
  # Set NIXSTASIS_DEV_BIND_ALL=true to bind on 0.0.0.0 (needed for dockerized runtime E2E on non-Linux hosts).
  http: [ip: endpoint_ip, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "4ASsRINPyhMqO2RRCiXHBM7y04vDBtVU0Bc/kSxtcNIByRxeukxzBXI3WOivnmT7",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:nixstasis, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:nixstasis, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :nixstasis, NixstasisWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/nixstasis_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

config :nixstasis, :e2e,
  allowed_env_labels: ["local"],
  protocol_versions: ["1"],
  environments: %{
    "local" => %{
      base_url: "http://localhost:4000",
      seed_script: "priv/e2e/seed.exs"
    }
  },
  suites: %{
    "full" => ["auth", "dashboard", "create_record", "update_record", "logout"],
    "runtime" => ["runtime_linux_telemetry", "runtime_transport_contract", "runtime_transport_negative"],
    # Focused suite for validating optional custom step labels (step_id != action).
    "runtime_step_labels" => ["runtime_step_labels"]
  },
  log_dir: "priv/e2e/logs",
  report_dir: "priv/e2e/reports",
  retention: [
    enabled: true,
    retention_days: 14,
    max_run_count: 2000,
    max_log_bytes: 1_000_000_000,
    check_interval_ms: 60_000
  ]

config :nixstasis, :base_domain, "devices.example.com"
config :nixstasis, :local_browser_auth_fallback?, true

# Enable dev routes for dashboard and mailbox
config :nixstasis, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

config :live_debugger,
  disabled?: String.downcase(System.get_env("LIVE_DEBUGGER", "false")) not in ["1", "true", "yes"]

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
