import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :nixstasis, NixstasisWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

session_cookie_secure? =
  case System.get_env("NIXSTASIS_SESSION_COOKIE_SECURE", "true") |> String.trim() |> String.downcase() do
    value when value in ["1", "true", "yes"] -> true
    value when value in ["0", "false", "no"] -> false
    value -> raise "NIXSTASIS_SESSION_COOKIE_SECURE must be true or false, got: #{inspect(value)}"
  end

config :nixstasis, :session_options, secure: session_cookie_secure?

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
