repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: ".*/vendor/.*.(css|js|map|ts)$"
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/crate-ci/typos
    rev: v1.43.1
    hooks:
      - id: typos
        exclude: "(^\\.specify/.*|.*/vendor/.*)"

  - repo: https://codeberg.org/frnmst/md-toc
    rev: "9.0.0"
    hooks:
      - id: md-toc
        args: [-p, github, -l6]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.47.0
    hooks:
      - id: markdownlint
        exclude: "(^(specs|.specify)/.*md$|.*AGENTS.md$)"
        args:
          - -c
          - pyproject.toml
          - --configPointer
          - /tool/markdownlint
          - --fix
