"""Initial DB

Revision ID: 3431c5a7c8e9
Revises:
Create Date: 2025-11-23 16:36:48.193589

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "3431c5a7c8e9"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "devices",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("mac_address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ip_address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("last_seen", sa.DateTime(), nullable=True),
        sa.Column("account", sa.Integer(), nullable=True),
        sa.Column("store", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("door", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("software_version", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("firmware_version", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("remote_access_requested", sa.Boolean(), nullable=False),
        sa.Column("remote_access_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("remote_connection_string", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sa.Enum("OFFLINE", "ONLINE", name="statustype"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account", "store", "door", name="uq_device_triplet"),
        sa.UniqueConstraint("mac_address", name="uq_mac_address"),
    )
    op.create_table(
        "readers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("serial_number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("position", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("profile", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("tx_band", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("region", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("version", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sa.Enum("OFFLINE", "ONLINE", name="statustype"), nullable=False),
        sa.Column("finalized", sa.Boolean(), nullable=False),
        sa.Column("inventory", sa.Boolean(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("serial_number"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("readers")
    op.drop_table("devices")
    # ### end Alembic commands ###
