defmodule NixstasisWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :nixstasis

  # The session is stored in an encrypted, signed cookie.
  @session_options [
    store: :cookie,
    key: "_nixstasis_key",
    signing_salt: "V4QPsRsQ",
    encryption_salt: "3L6zzKAl",
    same_site: "Lax"
  ]

  @session_options Keyword.merge(
                     @session_options,
                     Application.compile_env(:nixstasis, :session_options, [])
                   )

  socket("/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]
  )

  socket("/socket", NixstasisWeb.UserSocket,
    websocket: true,
    longpoll: false
  )

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug(Plug.Static,
    at: "/",
    from: :nixstasis,
    gzip: not code_reloading?,
    only: NixstasisWeb.static_paths()
  )

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket("/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket)
    plug(Phoenix.LiveReloader)
    plug(Phoenix.CodeReloader)
    plug AshPhoenix.Plug.CheckCodegenStatus
    plug(Phoenix.Ecto.CheckRepoStatus, otp_app: :nixstasis)
  end

  plug(Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"
  )

  plug(Plug.RequestId)
  plug(Plug.Telemetry, event_prefix: [:phoenix, :endpoint])

  plug(Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json, AshJsonApi.Plug.Parser],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()
  )

  plug(Plug.MethodOverride)
  plug(Plug.Head)
  plug(Plug.Session, @session_options)
  plug(NixstasisWeb.Router)
end
