defmodule Nixstasis.Repo.Migrations.CommandAllowlistCategories do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:command_allowlist_entry_categories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")

      add :command_entry_id,
          references(:command_allowlist_entries,
            column: :id,
            name: "command_allowlist_entry_categories_command_entry_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :category_id, :uuid, null: false
    end

    create index(:command_allowlist_entry_categories, [:category_id])

    create index(:command_allowlist_entry_categories, [:command_entry_id])

    create table(:command_allowlist_categories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:command_allowlist_entry_categories) do
      modify :category_id,
             references(:command_allowlist_categories,
               column: :id,
               name: "command_allowlist_entry_categories_category_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create unique_index(:command_allowlist_entry_categories, [:command_entry_id, :category_id],
             name: "command_allowlist_entry_categories_unique_entry_category_index"
           )

    alter table(:command_allowlist_categories) do
      add :slug, :text, null: false
      add :display_name, :text, null: false
      add :description, :text, default: ""
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:command_allowlist_categories, [:slug])

    create unique_index(:command_allowlist_categories, [:slug], name: "command_allowlist_categories_unique_slug_index")
  end

  def down do
    drop_if_exists unique_index(:command_allowlist_categories, [:slug],
                     name: "command_allowlist_categories_unique_slug_index"
                   )

    drop_if_exists index(:command_allowlist_categories, [:slug])

    alter table(:command_allowlist_categories) do
      remove :updated_at
      remove :inserted_at
      remove :description
      remove :display_name
      remove :slug
    end

    drop_if_exists unique_index(:command_allowlist_entry_categories, [:command_entry_id, :category_id],
                     name: "command_allowlist_entry_categories_unique_entry_category_index"
                   )

    drop constraint(:command_allowlist_entry_categories, "command_allowlist_entry_categories_category_id_fkey")

    alter table(:command_allowlist_entry_categories) do
      modify :category_id, :uuid
    end

    drop table(:command_allowlist_categories)

    drop constraint(:command_allowlist_entry_categories, "command_allowlist_entry_categories_command_entry_id_fkey")

    drop_if_exists index(:command_allowlist_entry_categories, [:command_entry_id])

    drop_if_exists index(:command_allowlist_entry_categories, [:category_id])

    drop table(:command_allowlist_entry_categories)
  end
end
