defmodule Nixstasis.Repo.Migrations.CommandPolicyAssignments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:command_policy_assignments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false, default: "pending"
      add :revision, :bigint, null: false
      add :version, :text, null: false
      add :resolved_policy, :map, null: false, default: %{}
      add :source_snapshot, :map, null: false, default: %{}
      add :drift_warning, :boolean, null: false, default: false
      add :queued_at, :utc_datetime
      add :acknowledged_at, :utc_datetime
      add :failed_at, :utc_datetime
      add :revoked_at, :utc_datetime
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")

      add :device_id,
          references(:devices,
            column: :id,
            name: "command_policy_assignments_device_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:command_policy_assignments, [:revision])

    create index(:command_policy_assignments, [:status])

    create index(:command_policy_assignments, [:device_id])

    create table(:command_policy_assignment_sources, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :source_kind, :text, null: false
      add :source_id, :uuid, null: false
      add :source_version, :bigint, null: false
      add :source_snapshot, :map, null: false, default: %{}
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")

      add :assignment_id,
          references(:command_policy_assignments,
            column: :id,
            name: "command_policy_assignment_sources_assignment_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:command_policy_assignment_sources, [:source_id])

    create index(:command_policy_assignment_sources, [:source_kind])

    create index(:command_policy_assignment_sources, [:assignment_id])
  end

  def down do
    drop constraint(:command_policy_assignment_sources, "command_policy_assignment_sources_assignment_id_fkey")

    drop_if_exists index(:command_policy_assignment_sources, [:assignment_id])

    drop_if_exists index(:command_policy_assignment_sources, [:source_kind])

    drop_if_exists index(:command_policy_assignment_sources, [:source_id])

    drop table(:command_policy_assignment_sources)

    drop constraint(:command_policy_assignments, "command_policy_assignments_device_id_fkey")

    drop_if_exists index(:command_policy_assignments, [:device_id])

    drop_if_exists index(:command_policy_assignments, [:status])

    drop_if_exists index(:command_policy_assignments, [:revision])

    drop table(:command_policy_assignments)
  end
end
