defmodule Nixstasis.Repo.Migrations.AddSshHostKeyTrust do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:devices) do
      add :ssh_host_key, :text
      add :ssh_host_key_pending, :text
      add :ssh_host_key_trusted_at, :utc_datetime_usec
      add :ssh_host_key_trusted_by, :text
      add :ssh_host_key_previous_fingerprint, :text
    end
  end

  def down do
    alter table(:devices) do
      remove :ssh_host_key_previous_fingerprint
      remove :ssh_host_key_trusted_by
      remove :ssh_host_key_trusted_at
      remove :ssh_host_key_pending
      remove :ssh_host_key
    end
  end
end
