defmodule Nixstasis.Repo.Migrations.DurableRemoteAccessLeases do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:remote_access_leases, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :owner_kind, :text, null: false
      add :owner_id, :uuid, null: false
      add :audit_owner, :text
      add :profile, :text, null: false
      add :expires_at, :utc_datetime_usec, null: false
      add :revoked_at, :utc_datetime_usec
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")

      add :device_id,
          references(:devices,
            column: :id,
            name: "remote_access_leases_device_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:remote_access_leases, [:owner_kind, :owner_id], unique: true)

    create index(:remote_access_leases, [:device_id, :inserted_at])

    alter table(:devices) do
      add :remote_access_default_profile, :text, null: false, default: "default"
    end

    execute "UPDATE devices SET remote_access_default_profile = remote_access_profile WHERE remote_access_requested = false"
  end

  def down do
    alter table(:devices) do
      remove :remote_access_default_profile
    end

    drop constraint(:remote_access_leases, "remote_access_leases_device_id_fkey")

    drop_if_exists index(:remote_access_leases, [:device_id, :inserted_at])

    drop_if_exists index(:remote_access_leases, [:owner_kind, :owner_id])

    drop table(:remote_access_leases)
  end
end
