defmodule Nixstasis.Repo.Migrations.DashboardDeviceGroups do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:device_groups, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :name_key, :text, null: false
      add :description, :text, default: ""
      add :archived_at, :utc_datetime
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:device_groups, [:archived_at])

    create unique_index(:device_groups, [:name_key], name: "device_groups_unique_name_key_index")

    create table(:device_group_memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")

      add :group_id,
          references(:device_groups,
            column: :id,
            name: "device_group_memberships_group_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :device_id,
          references(:devices,
            column: :id,
            name: "device_group_memberships_device_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:device_group_memberships, [:device_id])

    create index(:device_group_memberships, [:group_id])

    create unique_index(:device_group_memberships, [:group_id, :device_id],
             name: "device_group_memberships_unique_group_device_index"
           )
  end

  def down do
    drop_if_exists unique_index(:device_group_memberships, [:group_id, :device_id],
                     name: "device_group_memberships_unique_group_device_index"
                   )

    drop constraint(:device_group_memberships, "device_group_memberships_group_id_fkey")

    drop constraint(:device_group_memberships, "device_group_memberships_device_id_fkey")

    drop_if_exists index(:device_group_memberships, [:group_id])

    drop_if_exists index(:device_group_memberships, [:device_id])

    drop table(:device_group_memberships)

    drop_if_exists unique_index(:device_groups, [:name_key], name: "device_groups_unique_name_key_index")

    drop_if_exists index(:device_groups, [:archived_at])

    drop table(:device_groups)
  end
end
