defmodule Nixstasis.Repo.Migrations.CommandCatalog do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:device_command_inventory_snapshots, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :schema_version, :bigint, null: false
      add :probe_catalog_version, :text, null: false
      add :observed_at, :utc_datetime, null: false
      add :architecture, :text, null: false
      add :os_release, :map, null: false, default: %{}
      add :os_family, :text
      add :package_manager, :text, null: false
      add :packages, :map, null: false, default: %{}
      add :commands, :map, null: false, default: %{}
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")

      add :device_id,
          references(:devices,
            column: :id,
            name: "device_command_inventory_snapshots_device_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:device_command_inventory_snapshots, [:commands], using: "gin")

    create index(:device_command_inventory_snapshots, [:packages], using: "gin")

    create index(:device_command_inventory_snapshots, [:os_family])

    create index(:device_command_inventory_snapshots, [:observed_at])

    create index(:device_command_inventory_snapshots, [:probe_catalog_version])

    create index(:device_command_inventory_snapshots, [:device_id])

    create unique_index(:device_command_inventory_snapshots, [:device_id],
             name: "device_command_inventory_snapshots_unique_device_snapshot_index"
           )

    create table(:command_catalog_package_mappings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :os_family, :text, null: false
      add :package_manager, :text, null: false
      add :package_name, :text, null: false
      add :command_path, :text, null: false
      add :install_hint, :text, default: ""
      add :supported, :boolean, null: false, default: true
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :catalog_command_id, :uuid, null: false
    end

    create index(:command_catalog_package_mappings, [:package_name])

    create index(:command_catalog_package_mappings, [:os_family])

    create index(:command_catalog_package_mappings, [:catalog_command_id])

    create table(:command_catalog_commands, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:command_catalog_package_mappings) do
      modify :catalog_command_id,
             references(:command_catalog_commands,
               column: :id,
               name: "command_catalog_package_mappings_catalog_command_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create unique_index(:command_catalog_package_mappings, [:catalog_command_id, :os_family, :command_path],
             name: "command_catalog_mapping_command_os_path_idx"
           )

    alter table(:command_catalog_commands) do
      add :name, :text, null: false
      add :name_key, :text, null: false
      add :display_name, :text, null: false
      add :description, :text, default: ""
      add :category_slugs, {:array, :text}, null: false, default: []
      add :risk_notes, :text, default: ""
      add :install_guidance, :text, default: ""
      add :current_version, :bigint, null: false, default: 1
      add :active, :boolean, null: false, default: true
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:command_catalog_commands, [:category_slugs], using: "gin")

    create index(:command_catalog_commands, [:active])

    create index(:command_catalog_commands, [:name_key])

    create unique_index(:command_catalog_commands, [:name_key], name: "command_catalog_commands_unique_name_key_index")

    create table(:command_catalog_categories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :slug, :text, null: false
      add :display_name, :text, null: false
      add :description, :text, default: ""
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:command_catalog_categories, [:slug])

    create unique_index(:command_catalog_categories, [:slug], name: "command_catalog_categories_unique_slug_index")
  end

  def down do
    drop_if_exists unique_index(:command_catalog_categories, [:slug],
                     name: "command_catalog_categories_unique_slug_index"
                   )

    drop_if_exists index(:command_catalog_categories, [:slug])

    drop table(:command_catalog_categories)

    drop_if_exists unique_index(:command_catalog_commands, [:name_key],
                     name: "command_catalog_commands_unique_name_key_index"
                   )

    drop_if_exists index(:command_catalog_commands, [:name_key])

    drop_if_exists index(:command_catalog_commands, [:active])

    drop_if_exists index(:command_catalog_commands, [:category_slugs])

    alter table(:command_catalog_commands) do
      remove :updated_at
      remove :inserted_at
      remove :active
      remove :current_version
      remove :install_guidance
      remove :risk_notes
      remove :category_slugs
      remove :description
      remove :display_name
      remove :name_key
      remove :name
    end

    drop_if_exists unique_index(:command_catalog_package_mappings, [:catalog_command_id, :os_family, :command_path],
                     name: "command_catalog_mapping_command_os_path_idx"
                   )

    drop constraint(:command_catalog_package_mappings, "command_catalog_package_mappings_catalog_command_id_fkey")

    alter table(:command_catalog_package_mappings) do
      modify :catalog_command_id, :uuid
    end

    drop table(:command_catalog_commands)

    drop_if_exists index(:command_catalog_package_mappings, [:catalog_command_id])

    drop_if_exists index(:command_catalog_package_mappings, [:os_family])

    drop_if_exists index(:command_catalog_package_mappings, [:package_name])

    drop table(:command_catalog_package_mappings)

    drop_if_exists unique_index(:device_command_inventory_snapshots, [:device_id],
                     name: "device_command_inventory_snapshots_unique_device_snapshot_index"
                   )

    drop constraint(:device_command_inventory_snapshots, "device_command_inventory_snapshots_device_id_fkey")

    drop_if_exists index(:device_command_inventory_snapshots, [:device_id])

    drop_if_exists index(:device_command_inventory_snapshots, [:probe_catalog_version])

    drop_if_exists index(:device_command_inventory_snapshots, [:observed_at])

    drop_if_exists index(:device_command_inventory_snapshots, [:os_family])

    drop_if_exists index(:device_command_inventory_snapshots, [:packages])

    drop_if_exists index(:device_command_inventory_snapshots, [:commands])

    drop table(:device_command_inventory_snapshots)
  end
end
