defmodule Nixstasis.Repo.Migrations.CommandAllowlistEntries do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:command_allowlist_entry_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version, :bigint, null: false
      add :name, :text, null: false
      add :name_key, :text, null: false
      add :description, :text, default: ""
      add :command_path, :text, null: false
      add :archived_at, :utc_datetime
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :command_entry_id, :uuid, null: false
    end

    create index(:command_allowlist_entry_versions, [:name_key])

    create index(:command_allowlist_entry_versions, [:version])

    create index(:command_allowlist_entry_versions, [:command_entry_id])

    create table(:command_allowlist_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:command_allowlist_entry_versions) do
      modify :command_entry_id,
             references(:command_allowlist_entries,
               column: :id,
               name: "command_allowlist_entry_versions_command_entry_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create unique_index(:command_allowlist_entry_versions, [:command_entry_id, :version],
             name: "command_allowlist_entry_versions_unique_entry_version_index"
           )

    alter table(:command_allowlist_entries) do
      add :name, :text, null: false
      add :name_key, :text, null: false
      add :description, :text, default: ""
      add :command_path, :text, null: false
      add :current_version, :bigint, null: false, default: 1
      add :archived_at, :utc_datetime
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:command_allowlist_entries, [:archived_at])

    create index(:command_allowlist_entries, [:name_key])

    create unique_index(:command_allowlist_entries, [:name_key],
             name: "command_allowlist_entries_unique_name_key_index"
           )
  end

  def down do
    drop_if_exists unique_index(:command_allowlist_entries, [:name_key],
                     name: "command_allowlist_entries_unique_name_key_index"
                   )

    drop_if_exists index(:command_allowlist_entries, [:name_key])

    drop_if_exists index(:command_allowlist_entries, [:archived_at])

    alter table(:command_allowlist_entries) do
      remove :updated_at
      remove :inserted_at
      remove :archived_at
      remove :current_version
      remove :command_path
      remove :description
      remove :name_key
      remove :name
    end

    drop_if_exists unique_index(:command_allowlist_entry_versions, [:command_entry_id, :version],
                     name: "command_allowlist_entry_versions_unique_entry_version_index"
                   )

    drop constraint(:command_allowlist_entry_versions, "command_allowlist_entry_versions_command_entry_id_fkey")

    alter table(:command_allowlist_entry_versions) do
      modify :command_entry_id, :uuid
    end

    drop table(:command_allowlist_entries)

    drop_if_exists index(:command_allowlist_entry_versions, [:command_entry_id])

    drop_if_exists index(:command_allowlist_entry_versions, [:version])

    drop_if_exists index(:command_allowlist_entry_versions, [:name_key])

    drop table(:command_allowlist_entry_versions)
  end
end
