defmodule Nixstasis.Repo.Migrations.AtomixosBootstrapProvisioning do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:provisioning_deliveries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :attempt_id, :uuid, null: false
      add :artifact_sha256, :text, null: false
      add :artifact_filename, :text, null: false
      add :artifact_size, :bigint, null: false
      add :state, :text, null: false, default: "submitting"
      add :actor_id, :text, null: false
      add :job_id, :text
      add :job_url, :text
      add :job_state, :text
      add :current_step, :text
      add :job_payload, :map, null: false, default: %{}
      add :result, :map, null: false, default: %{}
      add :error, :text
      add :rollback_status, :text
      add :started_at, :utc_datetime
      add :completed_at, :utc_datetime
      add :lease_withdrawn_at, :utc_datetime
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")

      add :device_id,
          references(:devices,
            column: :id,
            name: "provisioning_deliveries_device_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:provisioning_deliveries, [:attempt_id],
             name: "provisioning_deliveries_unique_attempt_id_index",
             unique: true
           )

    create index(:provisioning_deliveries, [:device_id, :artifact_sha256])

    create index(:provisioning_deliveries, [:state])

    create index(:provisioning_deliveries, [:artifact_sha256])

    create index(:provisioning_deliveries, [:device_id])
  end

  def down do
    drop constraint(:provisioning_deliveries, "provisioning_deliveries_device_id_fkey")

    drop_if_exists index(:provisioning_deliveries, [:device_id])

    drop_if_exists index(:provisioning_deliveries, [:artifact_sha256])

    drop_if_exists index(:provisioning_deliveries, [:state])

    drop_if_exists index(:provisioning_deliveries, [:device_id, :artifact_sha256])

    drop_if_exists index(:provisioning_deliveries, [:attempt_id],
                     name: "provisioning_deliveries_unique_attempt_id_index"
                   )

    drop table(:provisioning_deliveries)
  end
end
