defmodule Nixstasis.Repo.Migrations.CiFixPendingCodegen do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:telemetry_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :timestamp, :utc_datetime, null: false
      add :payload, :map, null: false, default: %{}
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :device_id, :uuid, null: false
    end

    create index(:telemetry_events, [:payload], using: "gin")

    create index(:telemetry_events, [:timestamp])

    create index(:telemetry_events, [:device_id])

    create table(:system_settings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :key, :text, null: false
      add :value, :map, null: false, default: %{}
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:system_settings, [:key], name: "system_settings_unique_key_index")

    create table(:pending_commands, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :command_payload, :map, null: false, default: %{}
      add :status, :text, null: false, default: "queued"
      add :queued_at, :utc_datetime, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :delivered_at, :utc_datetime
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :device_id, :uuid, null: false
    end

    create index(:pending_commands, [:status])

    create index(:pending_commands, [:device_id])

    create table(:devices, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:telemetry_events) do
      modify :device_id,
             references(:devices,
               column: :id,
               name: "telemetry_events_device_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:pending_commands) do
      modify :device_id,
             references(:devices,
               column: :id,
               name: "pending_commands_device_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:devices) do
      add :mac_address, :text, null: false
      add :product_name, :text
      add :account_number, :text
      add :ipv4_address, :text
      add :approval_status, :text, null: false, default: "pending"
      add :api_token_hash, :text
      add :last_seen_at, :utc_datetime
      add :schema, :map, null: false, default: %{}
      add :metadata, :map, null: false, default: %{}
      add :remote_access_requested, :boolean, null: false, default: false
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:devices, [:metadata], using: "gin")

    create index(:devices, [:schema], using: "gin")

    create index(:devices, [:approval_status])

    create index(:devices, [:product_name])

    create index(:devices, [:ipv4_address])

    create index(:devices, [:account_number])

    create unique_index(:devices, [:mac_address], name: "devices_unique_mac_address_index")

    create table(:custom_reports, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :name, :text, null: false
      add :config, :map, null: false
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:custom_reports, [:name], name: "custom_reports_unique_name_index")

    create table(:alerts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :type, :text, null: false
      add :status, :text, null: false, default: "active"
      add :message, :text, null: false
      add :triggered_at, :utc_datetime, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :rule_id, :bigint
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")

      add :device_id,
          references(:devices,
            column: :id,
            name: "alerts_device_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create index(:alerts, [:triggered_at])

    create index(:alerts, [:type])

    create index(:alerts, [:status])

    create index(:alerts, [:device_id])

    create table(:alert_rules, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :name, :text, null: false, default: "Untitled rule"
      add :product_name, :text, null: false
      add :condition_field, :text, null: false
      add :operator, :text, null: false
      add :threshold_value, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:alert_rules, [:product_name])

    create index(:alert_rules, [:name])
  end

  def down do
    drop_if_exists index(:alert_rules, [:name])

    drop_if_exists index(:alert_rules, [:product_name])

    drop table(:alert_rules)

    drop constraint(:alerts, "alerts_device_id_fkey")

    drop_if_exists index(:alerts, [:device_id])

    drop_if_exists index(:alerts, [:status])

    drop_if_exists index(:alerts, [:type])

    drop_if_exists index(:alerts, [:triggered_at])

    drop table(:alerts)

    drop_if_exists unique_index(:custom_reports, [:name], name: "custom_reports_unique_name_index")

    drop table(:custom_reports)

    drop_if_exists unique_index(:devices, [:mac_address], name: "devices_unique_mac_address_index")

    drop_if_exists index(:devices, [:account_number])

    drop_if_exists index(:devices, [:ipv4_address])

    drop_if_exists index(:devices, [:product_name])

    drop_if_exists index(:devices, [:approval_status])

    drop_if_exists index(:devices, [:schema])

    drop_if_exists index(:devices, [:metadata])

    alter table(:devices) do
      remove :updated_at
      remove :inserted_at
      remove :remote_access_requested
      remove :metadata
      remove :schema
      remove :last_seen_at
      remove :api_token_hash
      remove :approval_status
      remove :ipv4_address
      remove :account_number
      remove :product_name
      remove :mac_address
    end

    drop constraint(:pending_commands, "pending_commands_device_id_fkey")

    alter table(:pending_commands) do
      modify :device_id, :uuid
    end

    drop constraint(:telemetry_events, "telemetry_events_device_id_fkey")

    alter table(:telemetry_events) do
      modify :device_id, :uuid
    end

    drop table(:devices)

    drop_if_exists index(:pending_commands, [:device_id])

    drop_if_exists index(:pending_commands, [:status])

    drop table(:pending_commands)

    drop_if_exists unique_index(:system_settings, [:key], name: "system_settings_unique_key_index")

    drop table(:system_settings)

    drop_if_exists index(:telemetry_events, [:device_id])

    drop_if_exists index(:telemetry_events, [:timestamp])

    drop_if_exists index(:telemetry_events, [:payload])

    drop table(:telemetry_events)
  end
end
