defmodule Nixstasis.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create_if_not_exists(unique_index(:custom_reports, [:name], name: "custom_reports_unique_name_index"))
  end

  def down do
    drop_if_exists unique_index(:custom_reports, [:name], name: "custom_reports_unique_name_index")
  end
end
