defmodule Nixstasis.Repo.Migrations.AddRemoteAccessRouteProfiles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:devices) do
      add :remote_access_profile, :text, null: false, default: "default"
    end
  end

  def down do
    alter table(:devices) do
      remove :remote_access_profile
    end
  end
end
