name: Build Packages
run-name: Building Package for ${{ github.ref_name }}

on:
  push:
    tags:
      - "*/v*"
      - "v*"

jobs:
  check-configs:
    uses: ./.github/workflows/_check_configs.yml

  build-package:
    needs: check-configs
    name: Build Package

    strategy:
      matrix:
        arch: ${{ fromJSON(needs.check-configs.outputs.arches) }}
        distro: ${{ fromJSON(needs.check-configs.outputs.distros) }}

    runs-on: ${{ matrix.distro }}-${{ matrix.arch }}-ephemeral

    outputs:
      PREFIX: ${{ steps.setup.outputs.prefix }}
      PACKAGE: ${{ steps.setup.outputs.package }}
      VERSION: ${{ steps.build_package.outputs.version-number }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          sparse-checkout: "/${{ needs.check-configs.outputs.package }}"
          sparse-checkout-cone-mode: false
          fetch-depth: 0

      - name: Install UPX
        if: ${{ (contains(github.ref_name, 'caddy') || contains(github.ref_name, 'frp')) }}
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true

      - name: Install Go
        if: ${{ contains(github.ref_name, 'caddy') }}
        uses: actions/setup-go@v6
        with:
          go-version: 'stable' # Latest stable version

      - name: Package Setup
        id: setup
        env:
          PACKAGE: ${{ needs.check-configs.outputs.package }}
        run: |
          tar cf - --remove-files -C "${PACKAGE}/" . | tar xvf -
          rm -rf "packages"

          PREFIX="${PACKAGE#packages/}/"
          echo "PREFIX=${PREFIX}" | tee -a "${GITHUB_ENV}"

          {
            echo "prefix=${PREFIX}"
            echo "package=${PREFIX%/*}"
            echo 'package_options<<EOF'
            yq -o json < package_options.yml | jq '."atom-python3-token" = "${{ secrets.ORG_GIT_TOKEN }}"'
            echo EOF
          } >> "${GITHUB_OUTPUT}"

          rm package_options.yml

      - name: Build Package
        id: build_package
        uses: RobertDeRose/common-build-scripts/actions/package@v3
        with: ${{ fromJson(steps.setup.outputs.package_options) }}

  release-package:
    name: Release Package
    runs-on: ubuntu-24.04
    needs:
      - build-package
      - check-configs

    steps:
    - name: Make Release
      uses: RobertDeRose/common-build-scripts/actions/create-release@v3
      with:
        version: ${{ needs.build-package.outputs.VERSION }}
        version_prefix: ${{ needs.build-package.outputs.PREFIX }}
        title: ${{ needs.build-package.outputs.PACKAGE}} v${{ needs.build-package.outputs.VERSION }}
